phase: local

db:
  local:
    url: jdbc:mysql://localhost:3306/localdb
    username: localuser
    password: localpass

  development:
    url: jdbc:mysql://dev-server:3306/devdb
    username: devuser
    password: devpass

  production:
    url: jdbc:mysql://prod-server:3306/proddb
    username: produser
    password: prodpass
