package main.ch01.file

enum class FilePurpose {
    MAIN_BANNER,
    CATEGORY_BANNER,
    USER_PROFILE,
    SELLER_PROFILE,
    PRODUCT_THUMBNAIL,
    PRODUCT_DETAIL,
    LOADING_ANIMATION,
    PROMOTIONAL_ANIMATION,
    HIGH_QUALITY_IMAGE,
    RAW_IMAGE,
}
